# Generated by Django 6.1 on 2026-08-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/image/%y/%m/%d/'),
        ),
    ]
