# Generated by Django 6.1 on 2026-08-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produtos_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripiton', models.CharField(blank=True, max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='app/image/%y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
