# Generated by Django 6.1 on 2026-08-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_servico_delete_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descripiton',
            field=models.CharField(max_length=150),
        ),
    ]
