# Generated by Django 6.1 on 2026-08-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_servico_descripiton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('telefone', models.CharField(max_length=20)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartao')], max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico')),
            ],
        ),
    ]
