# Generated by Django 6.1 on 2026-08-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_agendamento'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(fields=('data', 'horario'), name='unique_agendamento_data_horario'),
        ),
    ]
